# .github/workflows/ml_pipeline.yml
name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python train_model.py

      - name: Run tests
        run: |
          pytest test_model.py

      - name: Deploy model
        run: |
          # Command to deploy your model (e.g., push to cloud)